"""created tables

Revision ID: 810f801ab798
Revises: aeda05b83a4f
Create Date: 2021-04-09 16:13:04.367643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810f801ab798'
down_revision = 'aeda05b83a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=5), nullable=True),
    sa.Column('possession', sa.String(length=5), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_event', sa.Date(), nullable=True),
    sa.Column('type_event', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('patronymic', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_number', sa.String(length=10), nullable=True),
    sa.Column('VIN', sa.String(length=17), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('models_auto', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport')
    op.drop_table('people')
    op.drop_table('insurance_policy')
    op.drop_table('insurance_event')
    op.drop_table('address')
    # ### end Alembic commands ###
