"""Добавлены поля в таблицу Company

Revision ID: f00cdd08c483
Revises: 810f801ab798
Create Date: 2021-04-17 09:13:03.352791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00cdd08c483'
down_revision = '810f801ab798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(), nullable=True))
    op.add_column('company', sa.Column('director', sa.String(), nullable=True))
    op.add_column('company', sa.Column('inn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'inn')
    op.drop_column('company', 'director')
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
